<a href="https://colab.research.google.com/github/Dra001ven/winemag-data/blob/main/wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [ ]:
pd.DataFrame ({'North': ['Abuja','jos','kasstina'], 'South':['lagos', None, None] }, index = ['index a', 'index b', 'indexc'])

            North  South
index a     Abuja  lagos
index b       jos   None
indexc   kasstina   None

In [5]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/your-dataset-name.csv')
df.head()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [6]:
wine_reviews = pd.read_csv("winemag-data_first150k.csv",index_col= 0)

wine_reviews.head()

FileNotFoundError: [Errno 2] No such file or directory: 'winemag-data_first150k.csv'

In [ ]:
my_wine = pd.DataFrame({'country':wine_reviews.country , 'Destination':wine_reviews.designation , 'price':wine_reviews.price })
print(my_wine)

       country                           Destination  price
0           US                     Martha's Vineyard  235.0
1        Spain  Carodorum Selección Especial Reserva  110.0
2           US         Special Selected Late Harvest   90.0
3           US                               Reserve   65.0
4       France                            La Brûlade   66.0
...        ...                                   ...    ...
150925   Italy                                   NaN   20.0
150926  France                        Cuvée Prestige   27.0
150927   Italy                         Terre di Dora   20.0
150928  France                       Grand Brut Rosé   52.0
150929   Italy                                   NaN   15.0

[150930 rows x 3 columns]

In [ ]:
import os
os.makedirs("/content/why", exist_ok=True)

my_wine.to_csv("/content/why/new_list.csv", index=False)

In [ ]:
review = wine_reviews.description
type(review)
review

0         This tremendous 100% varietal wine hails from ...
1         Ripe aromas of fig, blackberry and cassis are ...
2         Mac Watson honors the memory of a wine once ma...
3         This spent 20 months in 30% new French oak, an...
4         This is the top wine from La Bégude, named aft...
                                ...
150925    Many people feel Fiano represents southern Ita...
150926    Offers an intriguing nose with ginger, lime an...
150927    This classic example comes from a cru vineyard...
150928    A perfect salmon shade, with scents of peaches...
150929    More Pinot Grigios should taste like this. A r...
Name: description, Length: 150930, dtype: object

In [ ]:
first_value = wine_reviews.price.loc[0]
first_value

np.float64(235.0)

In [1]:
sample_reviews = wine_reviews.description.iloc[[1,2,3,5,8]]
sample_reviews

NameError: name 'wine_reviews' is not defined